INSERT INTO product (id, name) VALUES (1, 'Apple iPhone 15');
INSERT INTO product (id, name) VALUES (2, 'Samsung Galaxy S24');
INSERT INTO product (id, name) VALUES (3, 'Google Pixel 8');
INSERT INTO product (id, name) VALUES (4, 'OnePlus 12');
INSERT INTO product (id, name) VALUES (5, 'Sony Xperia 1 V');
INSERT INTO product (id, name) VALUES (6, 'Huawei P60 Pro');
INSERT INTO product (id, name) VALUES (7, 'Xiaomi 14 Pro');
INSERT INTO product (id, name) VALUES (8, 'Motorola Edge 40');
INSERT INTO product (id, name) VALUES (9, 'Nokia G50');
INSERT INTO product (id, name) VALUES (10, 'Nothing Phone 2');
INSERT INTO product (id, name) VALUES (11, 'Apple MacBook Air M2');
INSERT INTO product (id, name) VALUES (12, 'Apple MacBook Pro 14');
INSERT INTO product (id, name) VALUES (13, 'Dell XPS 13');
INSERT INTO product (id, name) VALUES (14, 'HP Spectre x360');
INSERT INTO product (id, name) VALUES (15, 'Lenovo ThinkPad X1 Carbon');
INSERT INTO product (id, name) VALUES (16, 'Microsoft Surface Laptop 5');
INSERT INTO product (id, name) VALUES (17, 'Asus ROG Zephyrus G14');
INSERT INTO product (id, name) VALUES (18, 'Acer Swift 3');
INSERT INTO product (id, name) VALUES (19, 'LG Gram 17');
INSERT INTO product (id, name) VALUES (20, 'Samsung Galaxy Book 3');
INSERT INTO product (id, name) VALUES (21, 'Sony WH-1000XM5');
INSERT INTO product (id, name) VALUES (22, 'Apple AirPods Pro 2');
INSERT INTO product (id, name) VALUES (23, 'Bose QuietComfort 45');
INSERT INTO product (id, name) VALUES (24, 'Sennheiser Momentum 4');
INSERT INTO product (id, name) VALUES (25, 'Beats Studio Pro');
INSERT INTO product (id, name) VALUES (26, 'Google Pixel Buds Pro');
INSERT INTO product (id, name) VALUES (27, 'Jabra Elite 10');
INSERT INTO product (id, name) VALUES (28, 'Anker Soundcore Liberty 4');
INSERT INTO product (id, name) VALUES (29, 'Sony WF-1000XM5');
INSERT INTO product (id, name) VALUES (30, 'Nothing Ear 2');
INSERT INTO product (id, name) VALUES (31, 'Canon EOS R6 Mark II');
INSERT INTO product (id, name) VALUES (32, 'Nikon Z6 II');
INSERT INTO product (id, name) VALUES (33, 'Sony Alpha A7 IV');
INSERT INTO product (id, name) VALUES (34, 'Fujifilm X-T5');
INSERT INTO product (id, name) VALUES (35, 'Panasonic Lumix S5 II');
INSERT INTO product (id, name) VALUES (36, 'GoPro Hero 12');
INSERT INTO product (id, name) VALUES (37, 'DJI Mini 4 Pro');
INSERT INTO product (id, name) VALUES (38, 'Insta360 X3');
INSERT INTO product (id, name) VALUES (39, 'Logitech MX Master 3S');
INSERT INTO product (id, name) VALUES (40, 'Razer DeathAdder V3');
INSERT INTO product (id, name) VALUES (41, 'Apple iPad Pro 12.9');
INSERT INTO product (id, name) VALUES (42, 'Samsung Galaxy Tab S9');
INSERT INTO product (id, name) VALUES (43, 'Amazon Kindle Paperwhite');
INSERT INTO product (id, name) VALUES (44, 'Microsoft Xbox Series X');
INSERT INTO product (id, name) VALUES (45, 'Sony PlayStation 5');
INSERT INTO product (id, name) VALUES (46, 'Nintendo Switch OLED');
INSERT INTO product (id, name) VALUES (47, 'Apple Watch Series 9');
INSERT INTO product (id, name) VALUES (48, 'Samsung Galaxy Watch6');
INSERT INTO product (id, name) VALUES (49, 'Garmin Forerunner 265');
INSERT INTO product (id, name) VALUES (50, 'Fitbit Charge 6');
INSERT INTO product (id, name) VALUES (51, 'Philips Hue Starter Kit');
INSERT INTO product (id, name) VALUES (52, 'Google Nest Hub 2nd Gen');
INSERT INTO product (id, name) VALUES (53, 'Amazon Echo Dot 5th Gen');
INSERT INTO product (id, name) VALUES (54, 'Ring Video Doorbell 4');
INSERT INTO product (id, name) VALUES (55, 'Arlo Pro 5S');
INSERT INTO product (id, name) VALUES (56, 'Eufy RoboVac X8');
INSERT INTO product (id, name) VALUES (57, 'iRobot Roomba j7');
INSERT INTO product (id, name) VALUES (58, 'Dyson V15 Detect');
INSERT INTO product (id, name) VALUES (59, 'Shark Stratos Cordless');
INSERT INTO product (id, name) VALUES (60, 'Instant Pot Duo Plus');
INSERT INTO product (id, name) VALUES (61, 'Ninja Air Fryer Max');
INSERT INTO product (id, name) VALUES (62, 'KitchenAid Stand Mixer Artisan');
INSERT INTO product (id, name) VALUES (63, 'Nespresso Vertuo Plus');
INSERT INTO product (id, name) VALUES (64, 'Breville Barista Express');
INSERT INTO product (id, name) VALUES (65, 'DeLonghi Magnifica Evo');
INSERT INTO product (id, name) VALUES (66, 'Sony Bravia XR A80L 55');
INSERT INTO product (id, name) VALUES (67, 'LG C3 OLED 55');
INSERT INTO product (id, name) VALUES (68, 'Samsung QN90C 55');
INSERT INTO product (id, name) VALUES (69, 'TCL 6 Series 55');
INSERT INTO product (id, name) VALUES (70, 'Hisense U8K 55');
INSERT INTO product (id, name) VALUES (71, 'Apple TV 4K');
INSERT INTO product (id, name) VALUES (72, 'Nvidia Shield TV Pro');
INSERT INTO product (id, name) VALUES (73, 'Roku Streaming Stick 4K');
INSERT INTO product (id, name) VALUES (74, 'Chromecast with Google TV');
INSERT INTO product (id, name) VALUES (75, 'TP
